# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import example_pb2 as example__pb2


class DuneStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.isMuadDib = channel.unary_unary(
                '/dune.Dune/isMuadDib',
                request_serializer=example__pb2.WeFoundHim.SerializeToString,
                response_deserializer=example__pb2.DidYouReally.FromString,
                )


class DuneServicer(object):
    """Missing associated documentation comment in .proto file."""

    def isMuadDib(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DuneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'isMuadDib': grpc.unary_unary_rpc_method_handler(
                    servicer.isMuadDib,
                    request_deserializer=example__pb2.WeFoundHim.FromString,
                    response_serializer=example__pb2.DidYouReally.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dune.Dune', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Dune(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def isMuadDib(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dune.Dune/isMuadDib',
            example__pb2.WeFoundHim.SerializeToString,
            example__pb2.DidYouReally.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
