# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='dune',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rexample.proto\x12\x04\x64une\"\x1d\n\nWeFoundHim\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0c\x44idYouReally\x12\x0f\n\x07message\x18\x01 \x01(\t2;\n\x04\x44une\x12\x33\n\tisMuadDib\x12\x10.dune.WeFoundHim\x1a\x12.dune.DidYouReally\"\x00\x62\x06proto3'
)




_WEFOUNDHIM = _descriptor.Descriptor(
  name='WeFoundHim',
  full_name='dune.WeFoundHim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='dune.WeFoundHim.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=52,
)


_DIDYOUREALLY = _descriptor.Descriptor(
  name='DidYouReally',
  full_name='dune.DidYouReally',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='dune.DidYouReally.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['WeFoundHim'] = _WEFOUNDHIM
DESCRIPTOR.message_types_by_name['DidYouReally'] = _DIDYOUREALLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WeFoundHim = _reflection.GeneratedProtocolMessageType('WeFoundHim', (_message.Message,), {
  'DESCRIPTOR' : _WEFOUNDHIM,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:dune.WeFoundHim)
  })
_sym_db.RegisterMessage(WeFoundHim)

DidYouReally = _reflection.GeneratedProtocolMessageType('DidYouReally', (_message.Message,), {
  'DESCRIPTOR' : _DIDYOUREALLY,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:dune.DidYouReally)
  })
_sym_db.RegisterMessage(DidYouReally)



_DUNE = _descriptor.ServiceDescriptor(
  name='Dune',
  full_name='dune.Dune',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=87,
  serialized_end=146,
  methods=[
  _descriptor.MethodDescriptor(
    name='isMuadDib',
    full_name='dune.Dune.isMuadDib',
    index=0,
    containing_service=None,
    input_type=_WEFOUNDHIM,
    output_type=_DIDYOUREALLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DUNE)

DESCRIPTOR.services_by_name['Dune'] = _DUNE

# @@protoc_insertion_point(module_scope)
